/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;


import Settings.ActionButton;
import Settings.IEdits;
import Settings.Text;
import javax.swing.JOptionPane;

/**
 *
 * @author alioz
 */
public class BaşvuruEkranı extends javax.swing.JFrame implements IEdits{

    
    /**
     * Creates new form BaşvuruEkranı
     */
    public BaşvuruEkranı() {
        initComponents();
        getEdits();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BaşvuruPanel = new javax.swing.JPanel();
        kişiselBilgilerLaber = new javax.swing.JLabel();
        adsoyadLabel = new javax.swing.JLabel();
        tckimlikLabel = new javax.swing.JLabel();
        AdsoyadText = new javax.swing.JTextField();
        tcKimlikText = new javax.swing.JTextField();
        TelnoLabel = new javax.swing.JLabel();
        TelnoText = new javax.swing.JTextField();
        KızlıkSoyadLabel = new javax.swing.JLabel();
        KızlıkSoyadText = new javax.swing.JTextField();
        DoğumTarihiLabel = new javax.swing.JLabel();
        DoğumYeriLabel = new javax.swing.JLabel();
        DoğumTarihiText = new javax.swing.JTextField();
        DoğumYeriText = new javax.swing.JTextField();
        BabaAdıLabel = new javax.swing.JLabel();
        BabaAdıText = new javax.swing.JTextField();
        BaşvurButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Başvuru Ekranı");

        BaşvuruPanel.setBackground(new java.awt.Color(255, 51, 51));

        kişiselBilgilerLaber.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        kişiselBilgilerLaber.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        kişiselBilgilerLaber.setText("Kişisel Bilgiler");
        kişiselBilgilerLaber.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        adsoyadLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        adsoyadLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        adsoyadLabel.setText("Ad Soyad:");

        tckimlikLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tckimlikLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        tckimlikLabel.setText("T.C Kimlik No:");

        AdsoyadText.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        tcKimlikText.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        TelnoLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TelnoLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        TelnoLabel.setText("Telefon Numarası:");

        TelnoText.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        KızlıkSoyadLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        KızlıkSoyadLabel.setText("Anne Kızlık Soyadı 2. Harf:");

        KızlıkSoyadText.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        DoğumTarihiLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        DoğumTarihiLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        DoğumTarihiLabel.setText("Doğum Tarihi:");

        DoğumYeriLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        DoğumYeriLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        DoğumYeriLabel.setText("Doğum Yeri:");

        DoğumTarihiText.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        DoğumYeriText.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        BabaAdıLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BabaAdıLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        BabaAdıLabel.setText("Baba Adı:");

        BaşvurButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BaşvurButton.setText("Başvur");
        BaşvurButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BaşvurButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BaşvurButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BaşvuruPanelLayout = new javax.swing.GroupLayout(BaşvuruPanel);
        BaşvuruPanel.setLayout(BaşvuruPanelLayout);
        BaşvuruPanelLayout.setHorizontalGroup(
            BaşvuruPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BaşvuruPanelLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(BaşvuruPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kişiselBilgilerLaber, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(BaşvuruPanelLayout.createSequentialGroup()
                        .addGroup(BaşvuruPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TelnoLabel)
                            .addGroup(BaşvuruPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(adsoyadLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tckimlikLabel))
                            .addComponent(KızlıkSoyadLabel)
                            .addComponent(DoğumTarihiLabel)
                            .addComponent(DoğumYeriLabel)
                            .addComponent(BabaAdıLabel))
                        .addGap(26, 26, 26)
                        .addGroup(BaşvuruPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tcKimlikText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AdsoyadText, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TelnoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(KızlıkSoyadText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DoğumTarihiText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DoğumYeriText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BabaAdıText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(217, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BaşvuruPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BaşvurButton)
                .addGap(149, 149, 149))
        );

        BaşvuruPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {BabaAdıLabel, DoğumTarihiLabel, DoğumYeriLabel, KızlıkSoyadLabel, TelnoLabel, adsoyadLabel, kişiselBilgilerLaber, tckimlikLabel});

        BaşvuruPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {AdsoyadText, BabaAdıText, DoğumTarihiText, DoğumYeriText, KızlıkSoyadText, TelnoText, tcKimlikText});

        BaşvuruPanelLayout.setVerticalGroup(
            BaşvuruPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BaşvuruPanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(kişiselBilgilerLaber)
                .addGap(39, 39, 39)
                .addGroup(BaşvuruPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adsoyadLabel)
                    .addComponent(AdsoyadText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(BaşvuruPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tckimlikLabel)
                    .addComponent(tcKimlikText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(BaşvuruPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TelnoLabel)
                    .addComponent(TelnoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(BaşvuruPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(KızlıkSoyadLabel)
                    .addComponent(KızlıkSoyadText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(BaşvuruPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DoğumTarihiLabel)
                    .addComponent(DoğumTarihiText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(BaşvuruPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DoğumYeriLabel)
                    .addComponent(DoğumYeriText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(BaşvuruPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BabaAdıText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BabaAdıLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BaşvurButton)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        BaşvuruPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {AdsoyadText, BabaAdıLabel, BabaAdıText, DoğumTarihiLabel, DoğumTarihiText, DoğumYeriLabel, DoğumYeriText, KızlıkSoyadLabel, KızlıkSoyadText, TelnoLabel, TelnoText, adsoyadLabel, kişiselBilgilerLaber, tcKimlikText, tckimlikLabel});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BaşvuruPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BaşvuruPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BaşvurButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BaşvurButtonActionPerformed
        if(this.AdsoyadText.getText().trim().equals("")|| this.tcKimlikText.getText().trim().equals("") || this.TelnoText.getText().trim().equals("") ||
                this.KızlıkSoyadText.getText().trim().equals("") || this.DoğumTarihiText.getText().trim().equals("") || this.DoğumYeriText.getText().trim().equals("")
                || this.BabaAdıText.getText().trim().equals("")){
            JOptionPane.showMessageDialog(this, "Lütfen tüm alanları doldurunuz.");
        }else{
            JOptionPane.showMessageDialog(this, "Başvurunuz alınmıştır.\nMüşteri numaranız : "+randomMüsteriNo()+"\nŞifreniz : "+randomŞifreAl());
            ActionButton.setVisible(this, new GirişEkranı());
        }
   
       
    }//GEN-LAST:event_BaşvurButtonActionPerformed

         
  
    
    
    private String randomMüsteriNo(){
    String müşterino;
    müşterino=String.valueOf(1000000+(int)(Math.random()*9000000));
    return müşterino;
}
private String randomŞifreAl(){
    String şifre;
    şifre=String.valueOf(1000+(int)(Math.random()*9000));
    return şifre;
    
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BaşvuruEkranı.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BaşvuruEkranı.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BaşvuruEkranı.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BaşvuruEkranı.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BaşvuruEkranı().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AdsoyadText;
    private javax.swing.JLabel BabaAdıLabel;
    private javax.swing.JTextField BabaAdıText;
    private javax.swing.JButton BaşvurButton;
    private javax.swing.JPanel BaşvuruPanel;
    private javax.swing.JLabel DoğumTarihiLabel;
    private javax.swing.JTextField DoğumTarihiText;
    private javax.swing.JLabel DoğumYeriLabel;
    private javax.swing.JTextField DoğumYeriText;
    private javax.swing.JLabel KızlıkSoyadLabel;
    private javax.swing.JTextField KızlıkSoyadText;
    private javax.swing.JLabel TelnoLabel;
    private javax.swing.JTextField TelnoText;
    private javax.swing.JLabel adsoyadLabel;
    private javax.swing.JLabel kişiselBilgilerLaber;
    private javax.swing.JTextField tcKimlikText;
    private javax.swing.JLabel tckimlikLabel;
    // End of variables declaration//GEN-END:variables

    @Override
    public void getEdits() {
        this.setLocationRelativeTo(null);
        BaşvuruPanel.setFocusable(true);
        Text.setOnlyAlphabet(AdsoyadText);
        Text.setOnlyNumber(tcKimlikText);
        Text.setOnlyNumber(TelnoText);
        Text.setOnlyAlphabet(KızlıkSoyadText);
        Text.setOnlyAlphabet(BabaAdıText);
        Text.setOnlyAlphabet(DoğumYeriText);
        
        
        
        
    }

   
}
