/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Settings.ActionButton;
import Settings.IEdits;
import Settings.Text;
import javax.swing.JOptionPane;


/**
 *
 * @author alioz
 */
public class EftHavaleEkranı extends javax.swing.JFrame implements IEdits{
    int gönderilcekMiktar=0;

    /**
     * Creates new form EftHavaleEkranı
     */
    public EftHavaleEkranı() {
        initComponents();
        getEdits();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HavalePanel = new javax.swing.JPanel();
        HavaleLabel = new javax.swing.JLabel();
        HavaleBakiye = new javax.swing.JLabel();
        UyarıLabel = new javax.swing.JLabel();
        MiktarLabel = new javax.swing.JLabel();
        MiktarText = new javax.swing.JTextField();
        HavaleButon = new javax.swing.JButton();
        Geriİcon = new javax.swing.JLabel();
        TckimlikHavale = new javax.swing.JLabel();
        TcText = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        HavalePanel.setBackground(new java.awt.Color(102, 102, 255));

        HavaleLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        HavaleLabel.setForeground(new java.awt.Color(255, 255, 255));
        HavaleLabel.setText("Toplam Bakiyeniz :");

        HavaleBakiye.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        HavaleBakiye.setText("(BAKİYE)");

        UyarıLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        UyarıLabel.setForeground(new java.awt.Color(255, 255, 255));
        UyarıLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        UyarıLabel.setText("TEK SEFERDE 10.000 TL GÖNDEREBİLİRSİNİZ.");

        MiktarLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        MiktarLabel.setForeground(new java.awt.Color(255, 255, 255));
        MiktarLabel.setText("Gönderilecek Miktar :");

        MiktarText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                MiktarTextKeyReleased(evt);
            }
        });

        HavaleButon.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        HavaleButon.setText("Para Gönder");
        HavaleButon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        HavaleButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HavaleButonActionPerformed(evt);
            }
        });

        Geriİcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconlar/icons8_left_arrow_64px.png"))); // NOI18N
        Geriİcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Geriİcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GeriİconMouseClicked(evt);
            }
        });

        TckimlikHavale.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TckimlikHavale.setForeground(new java.awt.Color(255, 255, 255));
        TckimlikHavale.setText("Alıcı T.C. Kimlik No :");

        javax.swing.GroupLayout HavalePanelLayout = new javax.swing.GroupLayout(HavalePanel);
        HavalePanel.setLayout(HavalePanelLayout);
        HavalePanelLayout.setHorizontalGroup(
            HavalePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HavalePanelLayout.createSequentialGroup()
                .addGroup(HavalePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HavalePanelLayout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addGroup(HavalePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(HavalePanelLayout.createSequentialGroup()
                                .addGroup(HavalePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(HavaleLabel)
                                    .addComponent(MiktarLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(TckimlikHavale, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(34, 34, 34)
                                .addGroup(HavalePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(HavaleBakiye, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                                    .addComponent(MiktarText)
                                    .addComponent(TcText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(UyarıLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(HavalePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Geriİcon)))
                .addContainerGap(181, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HavalePanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(HavaleButon)
                .addGap(68, 68, 68))
        );

        HavalePanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {HavaleBakiye, MiktarText, TcText});

        HavalePanelLayout.setVerticalGroup(
            HavalePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HavalePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Geriİcon, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(UyarıLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(HavalePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HavaleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HavaleBakiye))
                .addGap(32, 32, 32)
                .addGroup(HavalePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MiktarLabel)
                    .addComponent(MiktarText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(HavalePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TckimlikHavale, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TcText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addComponent(HavaleButon)
                .addGap(25, 25, 25))
        );

        HavalePanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {HavaleBakiye, MiktarText, TcText});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HavalePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HavalePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MiktarTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_MiktarTextKeyReleased
        String text=this.MiktarText.getText();
        if(!text.equals("")){
            this.gönderilcekMiktar=Integer.valueOf(text);
            if(this.gönderilcekMiktar>10000){
                this.gönderilcekMiktar=10000;
                MiktarText.setText(String.valueOf(this.gönderilcekMiktar));
            }
       }else{
            this.gönderilcekMiktar=0;
        }
        System.out.println(gönderilcekMiktar);

    }//GEN-LAST:event_MiktarTextKeyReleased

    private void HavaleButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HavaleButonActionPerformed
        if(this.MiktarText.getText().equals("") || this.MiktarText.getText().equals("0")|| this.TcText.getText().equals("")){
           JOptionPane.showMessageDialog(this, "Tüm alanları doldurunuz.");
       }else{
        
        JOptionPane.showMessageDialog(this, "İşlem Başarılı.\nGönderilen miktar: "+this.gönderilcekMiktar+" TL");
    }//GEN-LAST:event_HavaleButonActionPerformed
    }
    private void GeriİconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GeriİconMouseClicked
        ActionButton.setVisible(this, new HesapEkranı());
    }//GEN-LAST:event_GeriİconMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EftHavaleEkranı.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EftHavaleEkranı.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EftHavaleEkranı.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EftHavaleEkranı.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EftHavaleEkranı().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Geriİcon;
    private javax.swing.JLabel HavaleBakiye;
    private javax.swing.JButton HavaleButon;
    private javax.swing.JLabel HavaleLabel;
    private javax.swing.JPanel HavalePanel;
    private javax.swing.JLabel MiktarLabel;
    private javax.swing.JTextField MiktarText;
    private javax.swing.JTextField TcText;
    private javax.swing.JLabel TckimlikHavale;
    private javax.swing.JLabel UyarıLabel;
    // End of variables declaration//GEN-END:variables

    @Override
    public void getEdits() {
        this.setLocationRelativeTo(null);
         HavalePanel.setFocusable(true);
         Text.setOnlyNumber(TcText);
         Text.setOnlyNumber(MiktarText);
        
    }
}
