/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;


import Settings.ActionButton;
import Settings.IEdits;
import Settings.Text;
import javax.swing.JOptionPane;

/**
 *
 * @author alioz
 */
public class GirişEkranı extends javax.swing.JFrame implements  IEdits{

    
    
    private String TcKimlikOriginal="T.C. No / Müşteri No";
    private String şifreOriginal="**********";
    public GirişEkranı() {
        initComponents();
        getEdits();
        
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GirişEkranıPanel = new javax.swing.JPanel();
        İyiGünlerLabel = new javax.swing.JLabel();
        şifreText = new javax.swing.JPasswordField();
        GirişButon = new javax.swing.JButton();
        SoruLabel = new javax.swing.JLabel();
        BaşvurButon = new javax.swing.JButton();
        kimlikText = new javax.swing.JTextField();
        ŞifreButon = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Giriş Ekranı");

        GirişEkranıPanel.setBackground(new java.awt.Color(102, 102, 255));

        İyiGünlerLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        İyiGünlerLabel.setForeground(new java.awt.Color(255, 255, 255));
        İyiGünlerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        İyiGünlerLabel.setText("İyi Günler");

        şifreText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        şifreText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                şifreTextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                şifreTextFocusLost(evt);
            }
        });

        GirişButon.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        GirişButon.setText("Giriş");
        GirişButon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        GirişButon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                GirişButonMouseEntered(evt);
            }
        });
        GirişButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GirişButonActionPerformed(evt);
            }
        });

        SoruLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        SoruLabel.setForeground(new java.awt.Color(255, 255, 255));
        SoruLabel.setText("Müşterimiz olmak ister misiniz ?");

        BaşvurButon.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BaşvurButon.setText("Başvur");
        BaşvurButon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BaşvurButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BaşvurButonActionPerformed(evt);
            }
        });

        kimlikText.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        kimlikText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                kimlikTextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                kimlikTextFocusLost(evt);
            }
        });

        ŞifreButon.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ŞifreButon.setText("Şifremi Unuttum");
        ŞifreButon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ŞifreButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ŞifreButonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout GirişEkranıPanelLayout = new javax.swing.GroupLayout(GirişEkranıPanel);
        GirişEkranıPanel.setLayout(GirişEkranıPanelLayout);
        GirişEkranıPanelLayout.setHorizontalGroup(
            GirişEkranıPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GirişEkranıPanelLayout.createSequentialGroup()
                .addGap(176, 176, 176)
                .addGroup(GirişEkranıPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(İyiGünlerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(şifreText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SoruLabel)
                    .addComponent(BaşvurButon)
                    .addComponent(kimlikText, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GirişButon)
                    .addComponent(ŞifreButon))
                .addContainerGap(174, Short.MAX_VALUE))
        );

        GirişEkranıPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {BaşvurButon, GirişButon, ŞifreButon});

        GirişEkranıPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {kimlikText, şifreText});

        GirişEkranıPanelLayout.setVerticalGroup(
            GirişEkranıPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GirişEkranıPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(İyiGünlerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(kimlikText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(şifreText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(GirişButon)
                .addGap(12, 12, 12)
                .addComponent(ŞifreButon)
                .addGap(18, 18, 18)
                .addComponent(SoruLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BaşvurButon)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        GirişEkranıPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {SoruLabel, kimlikText, şifreText});

        GirişEkranıPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {BaşvurButon, GirişButon, ŞifreButon});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(GirişEkranıPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(GirişEkranıPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public boolean bilgilerGecerlimi(){
        return !(this.kimlikText.getText().equals(this.TcKimlikOriginal) || String.valueOf(this.şifreText.getPassword()).equals(this.şifreOriginal));
    }
    private void GirişButonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GirişButonMouseEntered
        ActionButton.setVisible(this, new HesapEkranı());
    }//GEN-LAST:event_GirişButonMouseEntered

  
    private void şifreTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_şifreTextFocusGained
        Text.checkTextFocusGained(şifreText, şifreOriginal);
    }//GEN-LAST:event_şifreTextFocusGained

    private void şifreTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_şifreTextFocusLost
        Text.checkTextFocusLost(şifreText);
    }//GEN-LAST:event_şifreTextFocusLost

    private void GirişButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GirişButonActionPerformed
        
    }//GEN-LAST:event_GirişButonActionPerformed
    
    private void BaşvurButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BaşvurButonActionPerformed
        ActionButton.setVisible(this, new BaşvuruEkranı());
    }//GEN-LAST:event_BaşvurButonActionPerformed

    private void ŞifreButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ŞifreButonActionPerformed
        ActionButton.setVisible(this, new ŞifreEkranı());
    }//GEN-LAST:event_ŞifreButonActionPerformed

    private void kimlikTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_kimlikTextFocusGained
        Text.checkTextFocusGained(kimlikText, TcKimlikOriginal);
    }//GEN-LAST:event_kimlikTextFocusGained

    private void kimlikTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_kimlikTextFocusLost
        Text.checkTextFocusLost(kimlikText);
    }//GEN-LAST:event_kimlikTextFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GirişEkranı.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GirişEkranı.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GirişEkranı.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GirişEkranı.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GirişEkranı().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BaşvurButon;
    private javax.swing.JButton GirişButon;
    private javax.swing.JPanel GirişEkranıPanel;
    private javax.swing.JLabel SoruLabel;
    private javax.swing.JTextField kimlikText;
    private javax.swing.JLabel İyiGünlerLabel;
    private javax.swing.JButton ŞifreButon;
    private javax.swing.JPasswordField şifreText;
    // End of variables declaration//GEN-END:variables

    @Override
    public void getEdits() {
        this.setLocationRelativeTo(null);//ekranı ortada açtırmak için.
        GirişEkranıPanel.setFocusable(true);// herhangi bir yere focuslanmadı
        kimlikText.setText(TcKimlikOriginal);
        şifreText.setText(şifreOriginal);
        Text.setOnlyNumber(kimlikText);
        
        
    }

   
}