/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;


import Settings.ActionButton;
import Settings.IEdits;

/**
 *
 * @author alioz
 */
public class HesapEkranı extends javax.swing.JFrame implements IEdits{

    /**
     * Creates new form HesapEkranı
     */
    public HesapEkranı() {
        initComponents();
        getEdits();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HesapEkranıPanel = new javax.swing.JPanel();
        HesapHoşgeldinLabel = new javax.swing.JLabel();
        bakiyeicon = new javax.swing.JLabel();
        bakiyeLaber = new javax.swing.JLabel();
        efthavaleicon = new javax.swing.JLabel();
        EFTHavaleButon = new javax.swing.JButton();
        parayatıricon = new javax.swing.JLabel();
        parayatırbuton = new javax.swing.JButton();
        ParaÇekİkon = new javax.swing.JLabel();
        ParaÇekButon = new javax.swing.JButton();
        LogOuticon = new javax.swing.JLabel();
        ÇıkışLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        HesapEkranıPanel.setBackground(new java.awt.Color(102, 102, 255));
        HesapEkranıPanel.setToolTipText("Hesap Ekranı");
        HesapEkranıPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        HesapHoşgeldinLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        HesapHoşgeldinLabel.setForeground(new java.awt.Color(255, 255, 255));
        HesapHoşgeldinLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        HesapHoşgeldinLabel.setText("HOŞ GELDİNİZ");
        HesapEkranıPanel.add(HesapHoşgeldinLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 198, -1));

        bakiyeicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconlar/turkishlira_icon.png"))); // NOI18N
        HesapEkranıPanel.add(bakiyeicon, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 66, 104));

        bakiyeLaber.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        bakiyeLaber.setText("BAKİYE");
        HesapEkranıPanel.add(bakiyeLaber, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, -1, -1));

        efthavaleicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconlar/moneytransfer.png"))); // NOI18N
        HesapEkranıPanel.add(efthavaleicon, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 280, 86, 70));

        EFTHavaleButon.setText("EFT-HAVALE");
        EFTHavaleButon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        EFTHavaleButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EFTHavaleButonActionPerformed(evt);
            }
        });
        HesapEkranıPanel.add(EFTHavaleButon, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 350, -1, -1));

        parayatıricon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconlar/icons8_safe_48px.png"))); // NOI18N
        HesapEkranıPanel.add(parayatıricon, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, 86, 67));

        parayatırbuton.setText("PARA YATIR");
        parayatırbuton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        parayatırbuton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parayatırbutonActionPerformed(evt);
            }
        });
        HesapEkranıPanel.add(parayatırbuton, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 350, -1, -1));

        ParaÇekİkon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconlar/icons8_money_60px.png"))); // NOI18N
        HesapEkranıPanel.add(ParaÇekİkon, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 86, 50));

        ParaÇekButon.setText("PARA ÇEK");
        ParaÇekButon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ParaÇekButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ParaÇekButonActionPerformed(evt);
            }
        });
        HesapEkranıPanel.add(ParaÇekButon, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 93, -1));

        LogOuticon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconlar/çıkış.png"))); // NOI18N
        LogOuticon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LogOuticon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogOuticonMouseClicked(evt);
            }
        });
        HesapEkranıPanel.add(LogOuticon, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 50, 60));

        ÇıkışLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        ÇıkışLabel.setText("Çıkış");
        HesapEkranıPanel.add(ÇıkışLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 50, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HesapEkranıPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HesapEkranıPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ParaÇekButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ParaÇekButonActionPerformed
        ActionButton.setVisible(this, new ParaÇekmeEkranı());
    }//GEN-LAST:event_ParaÇekButonActionPerformed

    private void parayatırbutonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parayatırbutonActionPerformed
        ActionButton.setVisible(this, new ParaYatırmaEkranı());
    }//GEN-LAST:event_parayatırbutonActionPerformed

    private void EFTHavaleButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EFTHavaleButonActionPerformed
        ActionButton.setVisible(this, new EftHavaleEkranı());
    }//GEN-LAST:event_EFTHavaleButonActionPerformed

    private void LogOuticonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogOuticonMouseClicked
        ActionButton.setVisible(this, new GirişEkranı());
    }//GEN-LAST:event_LogOuticonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HesapEkranı.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HesapEkranı.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HesapEkranı.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HesapEkranı.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HesapEkranı().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EFTHavaleButon;
    private javax.swing.JPanel HesapEkranıPanel;
    private javax.swing.JLabel HesapHoşgeldinLabel;
    private javax.swing.JLabel LogOuticon;
    private javax.swing.JButton ParaÇekButon;
    private javax.swing.JLabel ParaÇekİkon;
    private javax.swing.JLabel bakiyeLaber;
    private javax.swing.JLabel bakiyeicon;
    private javax.swing.JLabel efthavaleicon;
    private javax.swing.JButton parayatırbuton;
    private javax.swing.JLabel parayatıricon;
    private javax.swing.JLabel ÇıkışLabel;
    // End of variables declaration//GEN-END:variables

    @Override
    public void getEdits() {
         this.setLocationRelativeTo(null);
         HesapEkranıPanel.setFocusable(true);
         
    }

    
}
