/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Settings.ActionButton;
import Settings.IEdits;
import Settings.Text;
import javax.swing.JOptionPane;

/**
 *
 * @author alioz
 */
public class ParaÇekmeEkranı extends javax.swing.JFrame implements IEdits{
    private int çekilecekMiktar=0;

    /**
     * Creates new form ParaÇekmeEkranı
     */
    public ParaÇekmeEkranı() {
        initComponents();
        getEdits();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ParaÇekmePanel = new javax.swing.JPanel();
        ParaÇekmeBakiyeLabel = new javax.swing.JLabel();
        BakiyeLabel = new javax.swing.JLabel();
        UyarıLabel = new javax.swing.JLabel();
        MiktarLabel = new javax.swing.JLabel();
        MiktarText = new javax.swing.JTextField();
        ParaÇekButon = new javax.swing.JButton();
        Geriİcon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ParaÇekmePanel.setBackground(new java.awt.Color(102, 102, 255));

        ParaÇekmeBakiyeLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ParaÇekmeBakiyeLabel.setForeground(new java.awt.Color(255, 255, 255));
        ParaÇekmeBakiyeLabel.setText("Toplam Bakiyeniz :");

        BakiyeLabel.setText("(BAKİYE)");

        UyarıLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        UyarıLabel.setForeground(new java.awt.Color(255, 255, 255));
        UyarıLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        UyarıLabel.setText("TEK SEFERDE 5000 TL ÇEKEBİLİRSİNİZ.");

        MiktarLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        MiktarLabel.setForeground(new java.awt.Color(255, 255, 255));
        MiktarLabel.setText("Çekeceğiniz Miktar :");

        MiktarText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                MiktarTextKeyReleased(evt);
            }
        });

        ParaÇekButon.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ParaÇekButon.setText("Para Çek");
        ParaÇekButon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ParaÇekButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ParaÇekButonActionPerformed(evt);
            }
        });

        Geriİcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconlar/icons8_left_arrow_64px.png"))); // NOI18N
        Geriİcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Geriİcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GeriİconMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout ParaÇekmePanelLayout = new javax.swing.GroupLayout(ParaÇekmePanel);
        ParaÇekmePanel.setLayout(ParaÇekmePanelLayout);
        ParaÇekmePanelLayout.setHorizontalGroup(
            ParaÇekmePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ParaÇekmePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ParaÇekButon)
                .addGap(92, 92, 92))
            .addGroup(ParaÇekmePanelLayout.createSequentialGroup()
                .addGroup(ParaÇekmePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ParaÇekmePanelLayout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addGroup(ParaÇekmePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(UyarıLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(ParaÇekmePanelLayout.createSequentialGroup()
                                .addGroup(ParaÇekmePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ParaÇekmeBakiyeLabel)
                                    .addComponent(MiktarLabel))
                                .addGap(18, 18, 18)
                                .addGroup(ParaÇekmePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(MiktarText)
                                    .addComponent(BakiyeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)))))
                    .addGroup(ParaÇekmePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Geriİcon)))
                .addContainerGap(206, Short.MAX_VALUE))
        );

        ParaÇekmePanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {MiktarLabel, ParaÇekmeBakiyeLabel});

        ParaÇekmePanelLayout.setVerticalGroup(
            ParaÇekmePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ParaÇekmePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Geriİcon, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(UyarıLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(ParaÇekmePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ParaÇekmeBakiyeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BakiyeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(ParaÇekmePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MiktarText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MiktarLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(ParaÇekButon)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        ParaÇekmePanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {BakiyeLabel, MiktarLabel, MiktarText, ParaÇekmeBakiyeLabel});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ParaÇekmePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ParaÇekmePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ParaÇekButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ParaÇekButonActionPerformed
       if(this.MiktarText.getText().equals("") || this.MiktarText.getText().equals("0")){
           JOptionPane.showMessageDialog(ParaÇekmePanel, "Para miktarı girmediniz.");
       }else{
        
        JOptionPane.showMessageDialog(this, "İşlem Başarılı.\nÇekilen Miktar: "+this.çekilecekMiktar+" TL.");
    }//GEN-LAST:event_ParaÇekButonActionPerformed
    }
    private void GeriİconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GeriİconMouseClicked
        ActionButton.setVisible(this, new HesapEkranı());
    }//GEN-LAST:event_GeriİconMouseClicked

    private void MiktarTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_MiktarTextKeyReleased
        String text=this.MiktarText.getText();
        if(!text.equals("")){
            this.çekilecekMiktar=Integer.valueOf(text);
            if(this.çekilecekMiktar>5000){
                this.çekilecekMiktar=5000;
                MiktarText.setText(String.valueOf(this.çekilecekMiktar));
            }
        }else{
            this.çekilecekMiktar=0;
        }
      

    }//GEN-LAST:event_MiktarTextKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ParaÇekmeEkranı.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ParaÇekmeEkranı.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ParaÇekmeEkranı.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ParaÇekmeEkranı.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ParaÇekmeEkranı().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BakiyeLabel;
    private javax.swing.JLabel Geriİcon;
    private javax.swing.JLabel MiktarLabel;
    private javax.swing.JTextField MiktarText;
    private javax.swing.JButton ParaÇekButon;
    private javax.swing.JLabel ParaÇekmeBakiyeLabel;
    private javax.swing.JPanel ParaÇekmePanel;
    private javax.swing.JLabel UyarıLabel;
    // End of variables declaration//GEN-END:variables

    @Override
    public void getEdits() {
        this.setLocationRelativeTo(null);//ekranı ortada açtırmak için.
        ParaÇekmePanel.setFocusable(true);
        Text.setOnlyNumber(MiktarText);
        
    }
}
